openapi: 3.0.3
info:
  title: Conversations API
  version: 1.0.0
  description: Messaging and conversation management endpoints

paths:
  /conversations:
    get:
      summary: List conversations
      tags: [Conversations]
      security:
        - bearerAuth: []
      parameters:
        - name: locationId
          in: query
          required: false
          schema:
            type: string
            format: uuid
        - $ref: '#/components/parameters/LimitParam'
        - $ref: '#/components/parameters/CursorParam'
        - name: filter[status]
          in: query
          schema:
            type: string
            enum: [open, closed, snoozed]
        - name: filter[channel]
          in: query
          schema:
            type: string
            enum: [email, sms, whatsapp, facebook, instagram, webchat]
        - name: filter[assigned]
          in: query
          schema:
            type: string
            enum: [me, unassigned, all]
        - name: filter[unread]
          in: query
          schema:
            type: boolean
        - name: sort
          in: query
          schema:
            type: string
            default: -lastMessageAt
      responses:
        '200':
          description: List of conversations
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Conversation'
                  pagination:
                    $ref: '#/components/schemas/Pagination'

    post:
      summary: Create conversation
      tags: [Conversations]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [locationId, contactId, channel]
              properties:
                locationId:
                  type: string
                  format: uuid
                contactId:
                  type: string
                  format: uuid
                channel:
                  type: string
                  enum: [email, sms, whatsapp, facebook, instagram, webchat]
                assignedTo:
                  type: string
                  format: uuid
      responses:
        '201':
          description: Conversation created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Conversation'

  /conversations/{conversationId}:
    parameters:
      - $ref: '#/components/parameters/ConversationIdParam'

    get:
      summary: Get conversation details
      tags: [Conversations]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Conversation details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Conversation'

    patch:
      summary: Update conversation
      tags: [Conversations]
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  enum: [open, closed, snoozed]
                assignedTo:
                  type: string
                  format: uuid
                snoozedUntil:
                  type: string
                  format: date-time
      responses:
        '200':
          description: Conversation updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Conversation'

    delete:
      summary: Delete conversation
      tags: [Conversations]
      security:
        - bearerAuth: []
      responses:
        '204':
          description: Conversation deleted

  /conversations/{conversationId}/messages:
    parameters:
      - $ref: '#/components/parameters/ConversationIdParam'

    get:
      summary: Get conversation messages
      tags: [Conversations]
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/LimitParam'
        - $ref: '#/components/parameters/CursorParam'
        - name: before
          in: query
          schema:
            type: string
            format: date-time
          description: Get messages before this timestamp
        - name: after
          in: query
          schema:
            type: string
            format: date-time
          description: Get messages after this timestamp
      responses:
        '200':
          description: Conversation messages
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Message'
                  pagination:
                    $ref: '#/components/schemas/Pagination'

    post:
      summary: Send message
      tags: [Conversations]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [type, content]
              properties:
                type:
                  type: string
                  enum: [text, image, video, audio, file, template]
                content:
                  type: string
                  description: Message content or template ID
                attachments:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                        enum: [image, video, audio, file]
                      url:
                        type: string
                        format: uri
                      filename:
                        type: string
                      size:
                        type: integer
                metadata:
                  type: object
                  description: Channel-specific metadata
                  additionalProperties: true
      responses:
        '201':
          description: Message sent
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'

  /conversations/{conversationId}/typing:
    parameters:
      - $ref: '#/components/parameters/ConversationIdParam'

    post:
      summary: Send typing indicator
      tags: [Conversations]
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                typing:
                  type: boolean
                  default: true
      responses:
        '204':
          description: Typing indicator sent

  /conversations/{conversationId}/read:
    parameters:
      - $ref: '#/components/parameters/ConversationIdParam'

    post:
      summary: Mark conversation as read
      tags: [Conversations]
      security:
        - bearerAuth: []
      responses:
        '204':
          description: Conversation marked as read

  /conversations/channels:
    get:
      summary: List available channels
      tags: [Conversations]
      security:
        - bearerAuth: []
      parameters:
        - name: locationId
          in: query
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Available channels
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Channel'

  /conversations/channels/{channelType}/configure:
    parameters:
      - name: channelType
        in: path
        required: true
        schema:
          type: string
          enum: [email, sms, whatsapp, facebook, instagram, webchat]

    post:
      summary: Configure channel
      tags: [Conversations]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [locationId]
              properties:
                locationId:
                  type: string
                  format: uuid
                config:
                  type: object
                  description: Channel-specific configuration
                  additionalProperties: true
      responses:
        '200':
          description: Channel configured
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Channel'

  /conversations/templates:
    get:
      summary: List message templates
      tags: [Conversations]
      security:
        - bearerAuth: []
      parameters:
        - name: locationId
          in: query
          required: false
          schema:
            type: string
            format: uuid
        - name: channel
          in: query
          schema:
            type: string
            enum: [email, sms, whatsapp]
        - $ref: '#/components/parameters/LimitParam'
        - $ref: '#/components/parameters/CursorParam'
      responses:
        '200':
          description: Message templates
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/MessageTemplate'
                  pagination:
                    $ref: '#/components/schemas/Pagination'

    post:
      summary: Create message template
      tags: [Conversations]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [locationId, name, content, channel]
              properties:
                locationId:
                  type: string
                  format: uuid
                name:
                  type: string
                  example: Welcome Message
                content:
                  type: string
                  example: "Hi {{firstName}}, welcome to {{companyName}}!"
                channel:
                  type: string
                  enum: [email, sms, whatsapp]
                category:
                  type: string
                  example: greeting
                variables:
                  type: array
                  items:
                    type: string
                  example: [firstName, companyName]
      responses:
        '201':
          description: Template created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageTemplate'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  parameters:
    ConversationIdParam:
      name: conversationId
      in: path
      required: true
      schema:
        type: string
        format: uuid

    LimitParam:
      name: limit
      in: query
      schema:
        type: integer
        default: 50
        maximum: 100

    CursorParam:
      name: cursor
      in: query
      schema:
        type: string

  schemas:
    Conversation:
      type: object
      properties:
        id:
          type: string
          format: uuid
        locationId:
          type: string
          format: uuid
        contact:
          type: object
          properties:
            id:
              type: string
              format: uuid
            name:
              type: string
            avatar:
              type: string
              format: uri
        channel:
          type: string
          enum: [email, sms, whatsapp, facebook, instagram, webchat]
        status:
          type: string
          enum: [open, closed, snoozed]
        assignedTo:
          type: object
          properties:
            id:
              type: string
              format: uuid
            name:
              type: string
        unreadCount:
          type: integer
        lastMessage:
          $ref: '#/components/schemas/Message'
        lastMessageAt:
          type: string
          format: date-time
        snoozedUntil:
          type: string
          format: date-time
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    Message:
      type: object
      properties:
        id:
          type: string
          format: uuid
        conversationId:
          type: string
          format: uuid
        type:
          type: string
          enum: [text, image, video, audio, file, template]
        direction:
          type: string
          enum: [inbound, outbound]
        content:
          type: string
        attachments:
          type: array
          items:
            type: object
            properties:
              type:
                type: string
              url:
                type: string
                format: uri
              filename:
                type: string
              size:
                type: integer
              thumbnail:
                type: string
                format: uri
        status:
          type: string
          enum: [sent, delivered, read, failed]
        sentBy:
          type: object
          properties:
            id:
              type: string
              format: uuid
            name:
              type: string
            type:
              type: string
              enum: [user, contact, system]
        metadata:
          type: object
          additionalProperties: true
        createdAt:
          type: string
          format: date-time
        deliveredAt:
          type: string
          format: date-time
        readAt:
          type: string
          format: date-time

    Channel:
      type: object
      properties:
        type:
          type: string
          enum: [email, sms, whatsapp, facebook, instagram, webchat]
        enabled:
          type: boolean
        configured:
          type: boolean
        config:
          type: object
          additionalProperties: true
        capabilities:
          type: array
          items:
            type: string
            enum: [text, image, video, audio, file, template, typing]

    MessageTemplate:
      type: object
      properties:
        id:
          type: string
          format: uuid
        locationId:
          type: string
          format: uuid
        name:
          type: string
        content:
          type: string
        channel:
          type: string
          enum: [email, sms, whatsapp]
        category:
          type: string
        variables:
          type: array
          items:
            type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    Pagination:
      type: object
      properties:
        nextCursor:
          type: string
        prevCursor:
          type: string
        hasMore:
          type: boolean
        total:
          type: integer

    Error:
      type: object
      properties:
        error:
          type: object
          properties:
            code:
              type: string
            message:
              type: string
            details:
              type: array
              items:
                type: object
            requestId:
              type: string
            timestamp:
              type: string
              format: date-time

  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
