openapi: 3.0.3
info:
  title: Locations API
  version: 1.0.0
  description: Sub-account/location management endpoints

paths:
  /locations:
    get:
      summary: List locations
      tags: [Locations]
      security:
        - bearerAuth: []
      parameters:
        - name: agencyId
          in: query
          required: false
          schema:
            type: string
            format: uuid
        - $ref: '#/components/parameters/LimitParam'
        - $ref: '#/components/parameters/CursorParam'
        - name: filter[status]
          in: query
          schema:
            type: string
            enum: [active, inactive, suspended]
        - name: sort
          in: query
          schema:
            type: string
            default: -createdAt
      responses:
        '200':
          description: List of locations
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Location'
                  pagination:
                    $ref: '#/components/schemas/Pagination'

    post:
      summary: Create location
      tags: [Locations]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [agencyId, name, email]
              properties:
                agencyId:
                  type: string
                  format: uuid
                name:
                  type: string
                  example: Downtown Office
                email:
                  type: string
                  format: email
                  example: downtown@acmeagency.com
                phone:
                  type: string
                  example: +1-555-111-2222
                address:
                  $ref: '#/components/schemas/Address'
                website:
                  type: string
                  format: uri
                logo:
                  type: string
                  format: uri
                settings:
                  $ref: '#/components/schemas/LocationSettings'
                businessHours:
                  $ref: '#/components/schemas/BusinessHours'
      responses:
        '201':
          description: Location created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Location'
        '400':
          $ref: '#/components/responses/BadRequest'

  /locations/{locationId}:
    parameters:
      - $ref: '#/components/parameters/LocationIdParam'

    get:
      summary: Get location details
      tags: [Locations]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Location details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Location'
        '404':
          $ref: '#/components/responses/NotFound'

    patch:
      summary: Update location
      tags: [Locations]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                  format: email
                phone:
                  type: string
                address:
                  $ref: '#/components/schemas/Address'
                website:
                  type: string
                  format: uri
                logo:
                  type: string
                  format: uri
                status:
                  type: string
                  enum: [active, inactive, suspended]
                settings:
                  $ref: '#/components/schemas/LocationSettings'
                businessHours:
                  $ref: '#/components/schemas/BusinessHours'
      responses:
        '200':
          description: Location updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Location'

    delete:
      summary: Delete location
      tags: [Locations]
      security:
        - bearerAuth: []
      responses:
        '204':
          description: Location deleted
        '409':
          description: Cannot delete location with active data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /locations/{locationId}/settings:
    parameters:
      - $ref: '#/components/parameters/LocationIdParam'

    get:
      summary: Get location settings
      tags: [Locations]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Location settings
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LocationSettings'

    patch:
      summary: Update location settings
      tags: [Locations]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LocationSettings'
      responses:
        '200':
          description: Settings updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LocationSettings'

  /locations/{locationId}/users:
    parameters:
      - $ref: '#/components/parameters/LocationIdParam'

    get:
      summary: List location users
      tags: [Locations, Users]
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/LimitParam'
        - $ref: '#/components/parameters/CursorParam'
      responses:
        '200':
          description: List of location users
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/LocationUser'
                  pagination:
                    $ref: '#/components/schemas/Pagination'

    post:
      summary: Add user to location
      tags: [Locations, Users]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, role]
              properties:
                email:
                  type: string
                  format: email
                role:
                  type: string
                  enum: [admin, user, viewer]
                permissions:
                  type: array
                  items:
                    type: string
      responses:
        '201':
          description: User added
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LocationUser'

  /locations/{locationId}/users/{userId}:
    parameters:
      - $ref: '#/components/parameters/LocationIdParam'
      - $ref: '#/components/parameters/UserIdParam'

    patch:
      summary: Update location user
      tags: [Locations, Users]
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                role:
                  type: string
                  enum: [admin, user, viewer]
                permissions:
                  type: array
                  items:
                    type: string
      responses:
        '200':
          description: User updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LocationUser'

    delete:
      summary: Remove user from location
      tags: [Locations, Users]
      security:
        - bearerAuth: []
      responses:
        '204':
          description: User removed

  /locations/{locationId}/stats:
    parameters:
      - $ref: '#/components/parameters/LocationIdParam'

    get:
      summary: Get location statistics
      tags: [Locations]
      security:
        - bearerAuth: []
      parameters:
        - name: startDate
          in: query
          schema:
            type: string
            format: date
        - name: endDate
          in: query
          schema:
            type: string
            format: date
      responses:
        '200':
          description: Location statistics
          content:
            application/json:
              schema:
                type: object
                properties:
                  contacts:
                    type: object
                    properties:
                      total:
                        type: integer
                      new:
                        type: integer
                      active:
                        type: integer
                  opportunities:
                    type: object
                    properties:
                      total:
                        type: integer
                      won:
                        type: integer
                      lost:
                        type: integer
                      revenue:
                        type: number
                  conversations:
                    type: object
                    properties:
                      total:
                        type: integer
                      unread:
                        type: integer
                      responseTime:
                        type: number
                        description: Average response time in minutes
                  appointments:
                    type: object
                    properties:
                      total:
                        type: integer
                      scheduled:
                        type: integer
                      completed:
                        type: integer
                      cancelled:
                        type: integer

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  parameters:
    LocationIdParam:
      name: locationId
      in: path
      required: true
      schema:
        type: string
        format: uuid

    UserIdParam:
      name: userId
      in: path
      required: true
      schema:
        type: string
        format: uuid

    LimitParam:
      name: limit
      in: query
      schema:
        type: integer
        default: 50
        maximum: 100

    CursorParam:
      name: cursor
      in: query
      schema:
        type: string

  schemas:
    Location:
      type: object
      properties:
        id:
          type: string
          format: uuid
        agencyId:
          type: string
          format: uuid
        name:
          type: string
        email:
          type: string
          format: email
        phone:
          type: string
        address:
          $ref: '#/components/schemas/Address'
        website:
          type: string
          format: uri
        logo:
          type: string
          format: uri
        status:
          type: string
          enum: [active, inactive, suspended]
        settings:
          $ref: '#/components/schemas/LocationSettings'
        businessHours:
          $ref: '#/components/schemas/BusinessHours'
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    Address:
      type: object
      properties:
        street:
          type: string
        city:
          type: string
        state:
          type: string
        country:
          type: string
        postalCode:
          type: string

    LocationSettings:
      type: object
      properties:
        timezone:
          type: string
          example: America/New_York
        language:
          type: string
          example: en
        currency:
          type: string
          example: USD
        emailSignature:
          type: string
        smsSignature:
          type: string
        autoResponders:
          type: object
          properties:
            email:
              type: boolean
            sms:
              type: boolean
            message:
              type: string
        notifications:
          type: object
          properties:
            newContact:
              type: boolean
            newMessage:
              type: boolean
            newOpportunity:
              type: boolean
            appointmentReminder:
              type: boolean
        integrations:
          type: object
          properties:
            calendar:
              type: object
              properties:
                provider:
                  type: string
                  enum: [google, outlook, apple]
                enabled:
                  type: boolean
            email:
              type: object
              properties:
                provider:
                  type: string
                  enum: [gmail, outlook, smtp]
                enabled:
                  type: boolean
            phone:
              type: object
              properties:
                provider:
                  type: string
                  enum: [twilio, vonage]
                enabled:
                  type: boolean

    BusinessHours:
      type: object
      properties:
        monday:
          $ref: '#/components/schemas/DaySchedule'
        tuesday:
          $ref: '#/components/schemas/DaySchedule'
        wednesday:
          $ref: '#/components/schemas/DaySchedule'
        thursday:
          $ref: '#/components/schemas/DaySchedule'
        friday:
          $ref: '#/components/schemas/DaySchedule'
        saturday:
          $ref: '#/components/schemas/DaySchedule'
        sunday:
          $ref: '#/components/schemas/DaySchedule'

    DaySchedule:
      type: object
      properties:
        enabled:
          type: boolean
        hours:
          type: array
          items:
            type: object
            properties:
              start:
                type: string
                format: time
                example: "09:00"
              end:
                type: string
                format: time
                example: "17:00"

    LocationUser:
      type: object
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
          format: email
        firstName:
          type: string
        lastName:
          type: string
        role:
          type: string
          enum: [admin, user, viewer]
        permissions:
          type: array
          items:
            type: string
        status:
          type: string
          enum: [active, pending, suspended]
        createdAt:
          type: string
          format: date-time

    Pagination:
      type: object
      properties:
        nextCursor:
          type: string
        prevCursor:
          type: string
        hasMore:
          type: boolean
        total:
          type: integer

    Error:
      type: object
      properties:
        error:
          type: object
          properties:
            code:
              type: string
            message:
              type: string
            details:
              type: array
              items:
                type: object
            requestId:
              type: string
            timestamp:
              type: string
              format: date-time

  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
